/*==============================================================
 * Auto-generated file.
 *
 * DO NOT EDIT MANUALLY.
 * Generated by export_to_c.m
 *==============================================================*/

#ifndef WEIGHTS_H
#define WEIGHTS_H

#ifdef __cplusplus
extern "C" {
#endif

#define INPUT_SIZE        784
#define INPUT_WITH_BIAS   785
#define HIDDEN_SIZE       150
#define OUTPUT_SIZE       10

extern const float V[INPUT_WITH_BIAS][HIDDEN_SIZE];
extern const float W[HIDDEN_SIZE][OUTPUT_SIZE];

extern const float A[HIDDEN_SIZE];
extern const float C[HIDDEN_SIZE];

#ifdef __cplusplus
}
#endif

#endif
